name: Lint

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: "Dockerfile"
